# -*- coding: utf-8 -*-
"""ejercicio

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wXq5D0J2ns6VcTSh9B5zV32JY9UQOcWz
"""

#Autor: Mayra
#imprimir la tabla de 2

#a=input("ingrese un numero")
#for i in range(1, 11):
    #resultado = 5 * i
   # print(f" x {i} = {resultado}")


   # --------------------------- suma o se sale
#numero = int(input("Ingrese un número "))

#if numero == -1:
    #print("Saliendo del programa")
#else:
   # resultado = numero * 2
  # print(f"Resultado: {resultado}")

#print("CHAO")

#--------------------------------- menores o mayores en una fiesta
#while True:
 #edad = int(input("Ingrese la edad"))

#  if 18 <= edad < 45:
#     print("Bienvenido a la fiesta.")
#  elif edad >= 45:
#     print("ten cuidado con la musica fuerte")
#  else:
#   print(" lo siento, no puede entrar a la fiesta")
#     print("es todo")


#--------------------------------------la hipotenusa

#cateto1 = float(input("longitud del primer cateto"))

#cateto2 = float(input("longitud del segunto cateto"))

#hipotenusa = (cateto1**2 + cateto2**2)

#print("la hipotenusa es de: ", hipotenusa)

#----------------------------la distancia entre dos personas

from math import sqrt

a1 = float(input("primera persona: "))
b2 = float(input("segunda persona: "))

distancia = sqrt((a1 - b2)**2 + (b2 - a1)**2)

print("La distancia de pepito y maría es de:", distancia, "cuadras")